### ISSUE TITLE
Include editable field in survey/response_read

### ISSUE THREAD

**Issue by jeroenooms** [ohmage/server#859]
@hongsudt it would be very helpful if the server can include a field in `survey_response/read` if the response can be modified (update/delete) by the current user.

It is really impractical to do this on the client. The client has to trace back the response to a certain campaign and then lookup which classes are associated with that campaign, and then look which roles the current user has within these each of the classes and then combine these roles to reverse engineer the server logic if the user can update the campaign. It is probably trivial to do it on the server.

**Comment by stevenolen** [comment]
@jeroenooms you've implemented the client way of handling this already, correct?

I just took a look through the survey_response/read call -- it's probably best not to touch it unless absolutely necessary. Additionally, since the call doesn't hold any class state at all, it's likely to dramatically increase the response time for these requests. 

Let's just call this a "wontfix" for ohmage 2.x.
