### ISSUE TITLE
opencpu visualization and data privacy?

### ISSUE THREAD

**Issue by gr21783** [ohmage/server#877]
Can you clarify how opencpu works for visualization?  We installed ohmage on an amazon server.  Is it sending our data to a third party for processing and then sending the processed data back to us?

**Comment by stevenolen** [comment]
Hi @gr21783, I'd be happy to!

The (now legacy) [gwt-based frontend](https://github.com/ohmage/gwt-front-end) called a few ohmage APIs that would spawn off external requests to an opencpu server (details of those APIs can be found [here](https://github.com/ohmage/server/wiki/Visualization-APIs)).

For the viz apis, ohmage makes those requests entirely based on the opencpu server listed in the `ohmage.preference` table.  You can view yours by logging in to the database and executing: `select * from preference where p_key = 'visualization_server_address';`.  opencpu is an open source project, so you can easily host your own instance and update that row to reflect your instance.  You may even be using a local version of opencpu if you've installed from the apt packages! Additionally, however, it should be noted that these APIs were only supported in opencpu through version `< 1.0`.  You can still get a legacy copy of opencpu with ubuntu 12.04 and [this](https://launchpad.net/~opencpu/+archive/ubuntu/ohmage-2.16) ppa. If you don't have an interest in using the viz tab of the gwt frontend, you could simply empty this row with no consequences (`update preference set p_value='' where p_key='visualization_server_address';`).  

Now on to the good stuff.  Since the gwt frontend isn't supported (and as of ohmage 2.17 we suggest the use of our suite of micro frontends) we use opencpu features only in one of the frontends, the [plotapp](https://github.com/mobilizingcs/plotapp).  The plotapp is actually an opencpu library that runs entirely on an opencpu server and opencpu makes requests to ohmage for data (through the normal ohmage survey response APIs).  In our infrastructure, we proxy plotapp requests to opencpu [via nginx](https://github.com/mobilizingcs-ops/chef-cens-ohmage/blob/master/templates/default/ohmage-nginx.conf.erb#L54-L64).

Given all of this, we've tried to write the visualization pieces with plenty of flexibility -- you only need to use opencpu to get these particular features -- and even then, you can very easily specify an opencpu server you trust, or explicitly remove whatever default server is in the list to ensure your data is not going anywhere you aren't expecting!
